In [25]:
import os
os.environ["TORCH_LOGS"] = "+dynamo_verbose,+inductor"
import torch
import torch.nn as nn
import torchvision
from torch.utils.data import DataLoader
# from torch.utils.tensorboard import  SummaryWriter
import einops
# writer=SummaryWriter('logs')
torch._dynamo.config.verbose = True
torch._dynamo.config.suppress_errors = False
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


In [18]:
transform=torchvision.transforms.Compose([torchvision.transforms.RandAugment(num_ops=2,magnitude=6),torchvision.transforms.ToTensor()])
cifar_trainset=torchvision.datasets.CIFAR10('CIFAR10',train=True,transform=transform,download=True)
cifar_testset=torchvision.datasets.CIFAR10('CIFAR10',train=False,transform=torchvision.transforms.ToTensor(),download=True)
print(len(cifar_trainset))
cifar_trainset,cifar_validateset=torch.utils.data.random_split(cifar_trainset,[40000,10000])
load_trainset=DataLoader(cifar_trainset,batch_size=64,shuffle=True,drop_last=True)
load_validateset=DataLoader(cifar_validateset,batch_size=64,shuffle=True,drop_last=True)
load_testset=DataLoader(cifar_testset,batch_size=64,drop_last=False)
print(cifar_testset[0][0].shape)

50000
torch.Size([3, 32, 32])


In [26]:
class residual_connection(nn.Module):
    def __init__(self,in_channel,hidden_channel,out_channel,kernel_size=3,stride=1,padding=1):
        super().__init__()
        self.conv1=nn.Conv2d(in_channel,hidden_channel,kernel_size=1,stride=1,padding=0)
        self.conv2=nn.Conv2d(hidden_channel,hidden_channel,kernel_size,padding=padding)
        self.conv3=nn.Conv2d(hidden_channel,out_channel,kernel_size=1,padding=0)
        self.silu=nn.SiLU()
        self.batchnorm1=nn.BatchNorm2d(in_channel)
        self.batchnorm2=nn.BatchNorm2d(hidden_channel)
        self.batchnorm3=nn.BatchNorm2d(hidden_channel)
    def forward(self,x):
        y=x.clone()
        x=self.batchnorm1(x)
        x=self.conv1(x)
        x=self.silu(x)
        x=self.batchnorm2(x)
        x=self.conv2(x)
        x=self.silu(x)
        x=self.batchnorm3(x)
        x=self.conv3(x)
        x=self.silu(x)
        x=x+y
        return x
class resnetblock(nn.Module):
    def __init__(self,in_channel,hidden_channel,out_channel,num_residual_connection=2,kernel_size=3,stride=1,padding=1):
        super().__init__()
        self.residual_connections=nn.ModuleList([residual_connection(in_channel,hidden_channel,out_channel,kernel_size,stride,padding) for _ in range(num_residual_connection)])
    def forward(self,x):
        for residual_connection in self.residual_connections:
            x=residual_connection(x)
        return x
class resnet(nn.Module):
    def __init__(self):
        super().__init__()
        self.batchnorm1 = nn.BatchNorm2d(3)
        self.conv1 = nn.Conv2d(3, 32, 5, padding=2)
        self.resnetblock1=resnetblock(32,16,32,2,5,1,padding=2)
        self.pool1 = nn.MaxPool2d(2)
        self.silu1 = nn.SiLU()

        # self.batchnorm2 = nn.BatchNorm2d(32)
        # self.conv2 = nn.Conv2d(32, 32, 5, padding=2)
        self.resnetblock2=resnetblock(32,16,32,2,5,1,padding=2)
        self.pool2 = nn.MaxPool2d(2)
        self.silu2 = nn.SiLU()

        self.batchnorm3 = nn.BatchNorm2d(32)
        self.conv3 = nn.Conv2d(32, 64, 5, padding=2)
        self.resnetblock3=resnetblock(64,16,64,2,5,1,padding=2)
        self.pool3 = nn.MaxPool2d(2)
        self.silu3 = nn.SiLU()

        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64 * 16, 64)
        self.silu4 = nn.SiLU()
        self.fc2 = nn.Linear(64, 10)
        
    #     # 初始化权重为 Xavier
    #     self._initialize_weights()
    
    # def _initialize_weights(self):
    #     """使用 Xavier 初始化所有卷积层和全连接层的权重"""
    #     for m in self.modules():
    #         if isinstance(m, (nn.Conv2d, nn.Linear)):
    #             nn.init.xavier_normal_(m.weight)
    #             if m.bias is not None:
    #                 nn.init.constant_(m.bias, 0)
    
    def forward(self,x):
        x=self.batchnorm1(x)
        x=self.conv1(x)
        x=self.resnetblock1(x)
        x=self.pool1(x)
        x=self.silu1(x)
        # x=self.batchnorm2(x)
        print(1)
        x=self.resnetblock2(x)
        x=self.pool2(x)
        x=self.silu2(x)
        x=self.batchnorm3(x)
        x=self.conv3(x)
        x=self.resnetblock3(x)
        x=self.pool3(x)
        x=self.silu3(x)
        x=self.flatten(x)
        x=self.silu4(self.fc1(x))
        x=self.fc2(x)
        return x
model=resnet()
model=model.to(device)
model=torch.compile(model,backend="inductor")
model=model.to(device)
test=torch.randn(2,3,32,32,device=device)
print(model(test))


1
tensor([[-0.0018,  0.0530,  0.0618,  0.1064,  0.0156, -0.1843,  0.0753, -0.0830,
          0.0086,  0.1542],
        [-0.1668,  0.1439,  0.0550,  0.1665,  0.0384, -0.2509,  0.1776, -0.0840,
         -0.2029,  0.0913]], device='cuda:0',
       grad_fn=<CompiledFunctionBackward>)


In [14]:
# 从 metric.py 导入 get_metrics 函数
# 如果没有 metric.py，可以使用下面的函数定义
# @torch.compile
def get_metrics(model,load_testset,beta=1,fault_tolerance=0):
    acc=torch.zeros(10,device=device)
    predict=torch.zeros(10,device=device)
    total=torch.zeros(10,device=device)
    if fault_tolerance:
        for data in load_testset:
            imgs,label=data
            imgs=imgs.to(device)
            label=label.to(device)
            ans=model(imgs)
            for i in range(10):
                acc[i]+=torch.sum(torch.sum(torch.topk(ans,1+fault_tolerance,dim=1).indices==label.unsqueeze(1),dim=-1)*(label==i)).item()
                total[i]+=torch.sum(label==i).item()
                predict[i]+=torch.sum(torch.topk(ans,1+fault_tolerance,dim=1).indices==i).item()
    else:
        for data in load_testset:
            imgs,label=data
            imgs=imgs.to(device)
            label=label.to(device)
            ans=model(imgs)
            for i in range(10):
                acc[i]+=torch.sum((torch.argmax(ans,axis=1)==label)*(label==i)).item()
                total[i]+=torch.sum(label==i).item()
                predict[i]+=torch.sum(torch.argmax(ans,axis=1)==i).item()
    precision=acc/predict
    recall=acc/total
    f1=precision*recall/(beta**0.5*precision+recall)*(1+beta**0.5)
    accuracy=torch.sum(acc)/torch.sum(total)
    return f1,accuracy,precision,recall

print(get_metrics(model,load_testset,fault_tolerance=0))


(tensor([   nan, 0.0208, 0.0175,    nan, 0.0036, 0.1795, 0.0150, 0.0450, 0.0019,
        0.0634], device='cuda:0'), tensor(0.1003, device='cuda:0'), tensor([   nan, 0.1897, 0.0699,    nan, 0.0206, 0.0997, 0.1143, 0.1357, 0.0263,
        0.1208], device='cuda:0'), tensor([0.0000, 0.0110, 0.0100, 0.0000, 0.0020, 0.9010, 0.0080, 0.0270, 0.0010,
        0.0430], device='cuda:0'))


In [7]:
class cifarmodel(nn.Module):
    def __init__(self):
        super().__init__()
        self.batchnorm1 = nn.BatchNorm2d(3)
        self.conv1 = nn.Conv2d(3,32,5,padding=2)
        self.silu1 = nn.SiLU()
        self.pool1 = nn.MaxPool2d(2)
        
        self.batchnorm2 = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32,32,5,padding=2)
        self.silu2 = nn.SiLU()
        self.pool2 = nn.MaxPool2d(2)
        
        self.batchnorm3 = nn.BatchNorm2d(32)
        self.conv3 = nn.Conv2d(32,64,5,padding=2)
        self.silu3 = nn.SiLU()
        self.pool3 = nn.MaxPool2d(2)
        
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64*16,64)
        self.silu4 = nn.SiLU()
        self.fc2 = nn.Linear(64,10)
    
    def forward(self,x):
        x = self.batchnorm1(x)
        x = self.conv1(x)
        x = self.silu1(x)
        x = self.pool1(x)
        
        x = self.batchnorm2(x)
        x = self.conv2(x)
        x = self.silu2(x)
        x = self.pool2(x)
        
        x = self.batchnorm3(x)
        x = self.conv3(x)
        x = self.silu3(x)
        x = self.pool3(x)
        
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.silu4(x)
        x = self.fc2(x)
        return x
model=cifarmodel()
model=model.to(device)

In [14]:
class ViT(nn.Module):
    def __init__(self,patch1=4,patch2=4,channel=3):
        super().__init__()
        self.patch1=patch1
        self.patch2=patch2
        self.tokenize=nn.Linear(patch1*patch2*channel,64)
        self.embedding=nn.parameter.Parameter(torch.randn(65,64,device=device),requires_grad=True)
        self.classembedding=nn.parameter.Parameter(torch.randn(64,device=device),requires_grad=True)
        self.transformer=nn.TransformerEncoder(nn.TransformerEncoderLayer(64,4,dim_feedforward=128,batch_first=True),num_layers=3)
        self.fc=nn.Linear(64,10)
    def forward(self,x):
        x=einops.rearrange(x,'batch channel (h patch1) (w patch2) -> batch channel h w (patch1 patch2)',patch1=self.patch1,patch2=self.patch2)
        x=einops.rearrange(x,'batch channel h w patch -> batch (h w) (channel patch)')
        x=self.tokenize(x)
        x=torch.cat((self.classembedding.unsqueeze(0).unsqueeze(0).expand(x.shape[0],-1,-1),x),dim=1)
        x=x+self.embedding.unsqueeze(0).expand(x.shape[0],-1,-1)
        x=self.transformer(x)
        x=self.fc(x[:,0])
        return x
model=ViT()
model=model.to(device)

In [15]:
optimizer=torch.optim.AdamW(model.parameters(),lr=0.01)
loss=nn.CrossEntropyLoss()
loss=loss.to(device)
for epoch in range(5):
    model.train()
    totalloss=0
    for data in load_trainset:
        imgs,label=data
        imgs=imgs.to(device)
        label=label.to(device)
        result=model(imgs)
        result_loss=loss(result,label)
        optimizer.zero_grad()
        result_loss.backward()
        optimizer.step()
        totalloss+=result_loss.item()
    print(f"epoch={epoch},loss={totalloss},",end='')
    model.eval()
    # writer.add_scalar(tag='loss',scalar_value=totalloss,global_step=epoch)
    with torch.no_grad():
        f1,acc,precision,recall=get_metrics(model,load_validateset)
        print(f"f1={f1.mean()},acc={acc}")
#         writer.add_scalar(tag='f1',scalar_value=f1.mean(),global_step=epoch)
#         writer.add_scalar(tag='acc',scalar_value=acc,global_step=epoch)
# writer.close()


epoch=0,loss=1059.5609992742538,f1=0.429234117269516,acc=0.4468148946762085
epoch=1,loss=782.2217890024185,f1=0.594811737537384,acc=0.5942507982254028
epoch=2,loss=687.1115230321884,f1=0.6230522394180298,acc=0.6335136294364929
epoch=3,loss=642.8954094648361,f1=0.631286084651947,acc=0.6317107081413269
epoch=4,loss=600.355072259903,f1=0.6649085283279419,acc=0.668870210647583


In [7]:
optimizer=torch.optim.AdamW(model.parameters(),lr=0.002)
scheduler=torch.optim.lr_scheduler.CosineAnnealingLR(optimizer,T_max=10)
loss=nn.CrossEntropyLoss()
loss=loss.to(device)
iters=len(load_trainset)
for epoch in range(10):
    model.train()
    totalloss=0
    for i,data in enumerate(load_trainset):
        imgs,label=data
        imgs=imgs.to(device)
        label=label.to(device)
        result=model(imgs)
        result_loss=loss(result,label)
        optimizer.zero_grad()
        result_loss.backward()
        optimizer.step()
        totalloss+=result_loss.item()
        scheduler.step()
    print(f"epoch={epoch},loss={totalloss},",end='')
    model.eval()
    writer.add_scalar(tag='loss',scalar_value=totalloss,global_step=epoch)
    with torch.no_grad():
        f1,acc,precision,recall=get_metrics(model,load_validateset)
        print(f"f1={f1.mean()},acc={acc}")
        writer.add_scalar(tag='f1',scalar_value=f1.mean(),global_step=epoch)
        writer.add_scalar(tag='acc',scalar_value=acc,global_step=epoch)
print(get_metrics(model,load_testset,fault_tolerance=0))
writer.close()

epoch=0,loss=915.1165279746056,f1=0.5945548415184021,acc=0.5979567170143127
epoch=1,loss=639.57175552845,f1=0.6767562031745911,acc=0.6763821840286255
epoch=2,loss=541.1374174952507,f1=0.7036246061325073,acc=0.706129789352417
epoch=3,loss=472.2331186234951,f1=0.7238993644714355,acc=0.72265625
epoch=4,loss=430.6004136800766,f1=0.7396185994148254,acc=0.7396835088729858
epoch=5,loss=401.7740491628647,f1=0.7353681921958923,acc=0.7369791865348816
epoch=6,loss=380.94164699316025,f1=0.7468838095664978,acc=0.7474960088729858
epoch=7,loss=354.4526949226856,f1=0.7571839690208435,acc=0.7566105723381042
epoch=8,loss=336.1994234919548,f1=0.7435879707336426,acc=0.7411859035491943
epoch=9,loss=320.28780180215836,f1=0.7635459899902344,acc=0.762620210647583
(tensor([0.7989, 0.9051, 0.6983, 0.6268, 0.7496, 0.7108, 0.8381, 0.8483, 0.8633,
        0.8709], device='cuda:0'), tensor(0.7891, device='cuda:0'), tensor([0.8667, 0.9294, 0.6190, 0.5967, 0.7714, 0.7556, 0.9001, 0.8893, 0.8093,
        0.8554], devi

In [8]:
import torch
print(torch.__version__)
model = torch.nn.Linear(10, 1)
compiled = torch.compile(model, mode="reduce-overhead")  # 或 "max-autotune"（后者在 Windows GPU 上可能受限）
print(compiled(torch.randn(5, 10)).shape)

cudagraph partition due to non gpu ops. Found from : 
   File "d:\Anaconda\envs\py312pt291cu128\Lib\site-packages\torch\_dynamo\external_utils.py", line 68, in inner
    return fn(*args, **kwargs)
  File "d:\Anaconda\envs\py312pt291cu128\Lib\site-packages\torch\nn\modules\linear.py", line 134, in forward
    return F.linear(input, self.weight, self.bias)



2.9.1+cu128
torch.Size([5, 1])
